### ISSUE TITLE
A way to login with Email code

### ISSUE THREAD

**Issue by iMrDJAi** [jarvis394/glitch-api#10]
Another Glitch API wrapper has this feature: [glitch.js](https://github.com/Zaedus/glitch.js#logged-in-user-examples).
I suggest to add it since it's a far better way to login than picking up the token manually from localstorage.

**Comment by jarvis394** [comment]
Wow, I never heard about other Glitch API libs! Definitely will try to implement this, also I'm thinking about a rewrite of this project because it seems not a good *piece of code* to me xD

**Comment by iMrDJAi** [comment]
Trust me bro it was very difficult to me to find both of these 2 projects. I did a really deep search for that! xD

**Comment by jarvis394** [comment]
Also, you can use [this example](https://github.com/jarvis394/glitch-api/blob/master/docs/examples/anonymous.js) to login anonymously, without manually getting a token.
