### ISSUE TITLE
token?

### ISSUE THREAD

**Issue by J-Tech-Foundation** [jarvis394/glitch-api#3]
how do i get a token for this?

**Comment by jarvis394** [comment]
You mean, on Glitch? Then go to the any project (e.g. [this](https://glitch.com/edit/#!/glapi)) and open DevTools (F12). Then run this in console:

```js
(JSON.parse(localStorage.getItem('cachedUser'))).persistentToken
```

Hope that helps!

**Comment by J-Tech-Foundation** [comment]
ok
